"""empty message

Revision ID: 19b124e1a394
Revises: c1faf7ef66b9
Create Date: 2021-01-13 19:22:25.825585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b124e1a394'
down_revision = 'c1faf7ef66b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('flow_file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'flow_file_url')
    # ### end Alembic commands ###
