"""empty message

Revision ID: 5069a0097f39
Revises: 19b124e1a394
Create Date: 2021-01-25 17:35:18.160597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5069a0097f39'
down_revision = '19b124e1a394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_readings', 'oc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_readings', sa.Column('oc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
