"""empty message

Revision ID: 6b97410df7de
Revises: be4086439aca
Create Date: 2020-12-05 19:10:51.952064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b97410df7de'
down_revision = 'be4086439aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_location', 'flow_direction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_location', sa.Column('flow_direction', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
