"""empty message

Revision ID: 76626710c973
Revises: c8fd28eb68a8
Create Date: 2021-01-03 10:28:21.423137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76626710c973'
down_revision = 'c8fd28eb68a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_readings', sa.Column('cycle_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_readings', 'cycle_desc')
    # ### end Alembic commands ###
