"""empty message

Revision ID: 81b8a1f61803
Revises: 5069a0097f39
Create Date: 2021-01-25 17:35:56.996906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b8a1f61803'
down_revision = '5069a0097f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_readings', sa.Column('oc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_readings', 'oc')
    # ### end Alembic commands ###
