"""empty message

Revision ID: 85e555a45d6d
Revises: fddcadfc3bff
Create Date: 2020-12-28 21:26:24.808753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e555a45d6d'
down_revision = 'fddcadfc3bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_readings', sa.Column('flow_dir', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_readings', 'flow_dir')
    # ### end Alembic commands ###
