"""empty message

Revision ID: b68b5feaf3b8
Revises: 
Create Date: 2020-12-31 22:18:29.022725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68b5feaf3b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('loc_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('loc_type', sa.String(), nullable=True),
    sa.Column('flow_direction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('has_missing_details', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_location_id', sa.Integer(), nullable=True),
    sa.Column('loc_id', sa.String(), nullable=True),
    sa.Column('flow_date', sa.Date(), nullable=True),
    sa.Column('oc', sa.String(), nullable=True),
    sa.Column('tsq', sa.Integer(), nullable=True),
    sa.Column('flow_dir', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_location_id'], ['pipeline_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_readings')
    op.drop_table('pipeline_location')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
