"""empty message

Revision ID: ba3e97b24f82
Revises: f4020f7412d4
Create Date: 2020-12-28 19:23:59.085564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3e97b24f82'
down_revision = 'f4020f7412d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_readings', sa.Column('loc_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_readings', 'loc_id')
    # ### end Alembic commands ###
