"""empty message

Revision ID: c1faf7ef66b9
Revises: 76626710c973
Create Date: 2021-01-10 14:09:55.079699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1faf7ef66b9'
down_revision = '76626710c973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('loc_file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'loc_file_url')
    # ### end Alembic commands ###
