"""empty message

Revision ID: c8fd28eb68a8
Revises: b68b5feaf3b8
Create Date: 2021-01-02 10:47:38.302305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fd28eb68a8'
down_revision = 'b68b5feaf3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('tsp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'tsp')
    # ### end Alembic commands ###
