"""empty message

Revision ID: efd8eb01066d
Revises: bac5eb80ae32
Create Date: 2020-11-30 21:26:20.379010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd8eb01066d'
down_revision = 'bac5eb80ae32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_location_id', sa.Integer(), nullable=True),
    sa.Column('flow_date', sa.Date(), nullable=True),
    sa.Column('oc', sa.Integer(), nullable=True),
    sa.Column('tsq', sa.Integer(), nullable=True),
    sa.Column('flow_dir', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_location_id'], ['pipeline_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'pipeline_location', 'pipelines', ['pipeline_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_location', type_='foreignkey')
    op.drop_table('flow_readings')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
