"""empty message

Revision ID: f4020f7412d4
Revises: 39f2466ac08d
Create Date: 2020-12-28 19:20:33.914666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4020f7412d4'
down_revision = '39f2466ac08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_readings', sa.Column('flow_loc_id', sa.Integer(), nullable=True))
    op.drop_constraint('flow_readings_pipeline_location_id_fkey', 'flow_readings', type_='foreignkey')
    op.create_foreign_key(None, 'flow_readings', 'pipeline_location', ['flow_loc_id'], ['loc_id'])
    op.drop_column('flow_readings', 'pipeline_location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_readings', sa.Column('pipeline_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'flow_readings', type_='foreignkey')
    op.create_foreign_key('flow_readings_pipeline_location_id_fkey', 'flow_readings', 'pipeline_location', ['pipeline_location_id'], ['id'])
    op.drop_column('flow_readings', 'flow_loc_id')
    # ### end Alembic commands ###
