"""empty message

Revision ID: fddcadfc3bff
Revises: ba3e97b24f82
Create Date: 2020-12-28 21:26:06.372665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddcadfc3bff'
down_revision = 'ba3e97b24f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_readings', 'flow_dir')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_readings', sa.Column('flow_dir', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
